theme: jekyll-theme-cayman
title: RW-VoiceShield Raw Waveform-based Adversarial Attack on One-shot Voice Conversion
# description: Jing-Tong Tzeng, Jeng-Lin Li, Huan-Yu Chen, Chun-Hsiang Huang, Chi-Hsin Chen, Cheng-Yi Fan, Edward Pei-Chuan Huang, Chi-Chun Lee
